# A descriptive name for the workflow
name: Sync main branch to learn branch

# Controls when the workflow will run.
# This workflow is triggered on any push event to the 'main' branch.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # The single job in this workflow, named 'sync'
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # A sequence of tasks called 'steps' that will be executed as part of the job
    steps:
      # Step 1: Check out the repository's code
      # This action checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches.
          # This is important because we need to reference the 'main' branch.
          fetch-depth: 0

      # Step 2: Push the 'main' branch to the 'learn' branch
      - name: Force push main to learn
        run: |
          # This command directly pushes the current state of the local 'main' branch
          # to the remote 'learn' branch.
          # The '--force' flag is used to overwrite the 'learn' branch completely,
          # ensuring it is an exact mirror of 'main'.
          git push origin main:learn --force
